### ISSUE TITLE
[BUG] Select width and height

### ISSUE THREAD

**Issue by guillaume60240** [PrestaShopCorp/puik#431]
# Context
When using the select component the width and height are not adapted for the content

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/b0936aa3-02c7-447e-aeac-b7000d38c036" />

If I override the style with:
``` css
.puik-select .puik-select-dropdown {
  width: max-content !important;
  height: 50vh !important;
}
```
It's all good:

<img width="775" alt="Image" src="https://github.com/user-attachments/assets/48a3a329-0d81-4519-9c4b-3259f0b6ffe0" />

# Reproduce link

# Steps to Reproduce

# Expected Behavior

# Current Behavior

# Additional comments
